In [1]:
## Data 2 Reviews

In [2]:
import os
os.listdir()

['.DS_Store',
 'regex.ipynb',
 'dictionary.ipynb',
 'datas',
 'regex',
 'dictionary',
 '.ipynb_checkpoints',
 'scrape_reviewstokped.ipynb']

In [3]:
import os

folder_path = "datas" 
files = os.listdir(folder_path)
files

['reviews_combined.json',
 'tokopedia_500_2.csv',
 'reviews_combined.csv',
 'products_combined.json',
 'tokopedia_500.csv',
 'products_combined.csv',
 'reviews_mapped.json']

In [7]:
#import json
#import glob
#import pandas as pd

# daftar file JSON yang mau digabung
files = ["datas/reviews_1.json", "datas/reviews_2.json", "datas/reviews_3.json", "datas/reviews_4.json", "datas/reviews_5.json"]

#all_reviews = []

#for f in files:
#    with open(f, "r", encoding="utf-8") as file:
#        try:
#            data = json.load(file)  # baca JSON
#            if isinstance(data, list):  # kalau list of reviews
#                all_reviews.extend(data)
#            else:  # kalau JSON object
#                all_reviews.append(data)
#        except json.JSONDecodeError:
#            print(f"⚠️ File {f} gagal dibaca atau kosong.")

# simpan ke file baru (gabungan)
#with open("datas/reviews_combined.json", "w", encoding="utf-8") as out_file:
#    json.dump(all_reviews, out_file, indent=2, ensure_ascii=False)

# opsional: juga bisa ke DataFrame
#df = pd.DataFrame(all_reviews)
#df.to_csv("datas/reviews_combined.csv", index=False, encoding="utf-8-sig")

#print(f"✅ Selesai, total reviews: {len(all_reviews)}")

In [8]:
import json
import pandas as pd
from collections import Counter
import re
import nltk
from nltk.corpus import stopwords

nltk.download("stopwords")

# Load file reviews.json
with open("datas/reviews_combined.json", "r", encoding="utf-8") as f:
    data = json.load(f)

texts = data

stop_words = set(stopwords.words("indonesian"))

all_words = []
for text in texts:
    words = re.findall(r"\w+", text.lower())
    filtered = [w for w in words if w not in stop_words]  # buang stopwords
    all_words.extend(filtered)

# Hitung frekuensi kata
counter = Counter(all_words)

top_100 = counter.most_common(100)

for word, freq in top_100:
    print(word, ":", freq)

bagus : 2990
nya : 2188
sesuai : 2145
barang : 1777
cepat : 1339
yg : 1226
banget : 1130
pengiriman : 1111
produk : 1011
aman : 1010
bahan : 936
semoga : 902
seller : 881
kualitas : 854
pas : 676
cocok : 664
beli : 661
harga : 655
pesanan : 647
packing : 597
enak : 574
ga : 541
ya : 531
warna : 529
mantap : 491
kasih : 480
bahannya : 470
terima : 469
rapi : 468
gak : 455
ukuran : 433
alhamdulillah : 422
paket : 418
bgt : 407
terimakasih : 405
1 : 396
awet : 386
suka : 386
toko : 384
respon : 378
oke : 372
deskripsi : 343
barangnya : 341
ok : 334
berfungsi : 328
tp : 328
ramah : 325
amanah : 320
lumayan : 317
tebal : 311
order : 301
udah : 297
pake : 274
makasih : 273
kurir : 273
anak : 271
2 : 271
sih : 270
coba : 264
nyaman : 264
aja : 261
dgn : 259
adem : 255
jg : 240
diterima : 234
rapih : 234
sdh : 224
amp : 220
pakai : 220
lembut : 220
kulit : 218
murah : 216
gambar : 215
sampe : 214
sukses : 214
kali : 213
keren : 213
kemasan : 204
pokoknya : 204
dipakai : 203
cepet : 199
udh : 199
mudah : 189
penjual : 182
original : 175
puas : 175
gk : 174
langganan : 173
d : 172
next : 167
langsung : 165
3 : 165
selamat : 164
tipis : 163
pesan : 160
tas : 159
fast : 156
thanks : 154
tebel : 154
bb : 153

[nltk_data] Downloading package stopwords to /Users/vinn/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [10]:
# top_100 is a list of tuples (word, freq)
df_top_words2 = pd.DataFrame(top_100, columns=['word', 'count'])
df_top_words2.head(40)

             word  count
0           bagus   2990
1             nya   2188
2          sesuai   2145
3          barang   1777
4           cepat   1339
5              yg   1226
6          banget   1130
7      pengiriman   1111
8          produk   1011
9            aman   1010
10          bahan    936
11         semoga    902
12         seller    881
13       kualitas    854
14            pas    676
15          cocok    664
16           beli    661
17          harga    655
18        pesanan    647
19        packing    597
20           enak    574
21             ga    541
22             ya    531
23          warna    529
24         mantap    491
25          kasih    480
26       bahannya    470
27         terima    469
28           rapi    468
29            gak    455
30         ukuran    433
31  alhamdulillah    422
32          paket    418
33            bgt    407
34    terimakasih    405
35              1    396
36           awet    386
37           suka    386
38           toko    384
39         respon    378

In [ ]:
## Data 1 Product

In [11]:
import pandas as pd

In [12]:
import pandas as pd

# daftar file CSV
files = ["datas/tokopedia_500.csv", "datas/tokopedia_500_2.csv"]

dfs = []
for f in files:
    try:
        df = pd.read_csv(f, encoding="utf-8-sig")
        dfs.append(df)
    except Exception as e:
        print(f"⚠️ Gagal baca {f}: {e}")

df_combined = pd.concat(dfs, ignore_index=True)

df_combined.to_csv("datas/products_combined.csv", index=False, encoding="utf-8-sig")

df_combined.to_json("datas/products_combined.json", orient="records", force_ascii=False, indent=2)

print(f"Selesai, total reviews: {len(df_combined)}")

Selesai, total reviews: 7944

In [13]:
df = pd.read_csv('datas/products_combined.csv')
df.head()

,product_id,product_name,url,description,price,sold_count,rating,total_stock,category,keyword
0,102050876661,ENOVE - Device Stylish 3 Warna | Bisa Dijeda |...,https://www.tokopedia.com/sixhill-id/enove-dev...,"Ashtray Enove, Gaya dan Performa dalam Satu Ge...",449000,2.0,5.0,20.0,Cup Holder Mobil,elektronik
1,100000430906,LIGE sub-merek FOXBOX Jam Tangan Pria Fashion ...,https://www.tokopedia.com/lige-jam-tangan/lige...,👉Spesifikasi (perkiraan):\nKeterangan:\n【Diame...,152150,183.0,4.6,62.0,Jam Tangan Analog Pria,elektronik
2,100585544236,HEPU HP-985 Power Bank 30.000 Mah 1 to 6,https://www.tokopedia.com/hepuofficialstore/he...,HEPU HP-985 Power Bank 30.000 Mah 1 to 6Ringka...,274800,1.0,NaN,6.0,Portable Power Bank,elektronik
3,15862783712,PESANAN KHUSUS CV. SYAILENDRA ELEKTRONIK,https://www.tokopedia.com/edmaelectronics/pesa...,Pesanan khusus,4200000,1.0,NaN,1.0,Cover Kipas Angin,elektronik
4,100626960960,Timbangan elektronik presisi tinggi timbangan ...,https://www.tokopedia.com/tianchengstore/timba...,"Pengenalan Fungsi:\nPresisi tinggi -0,01g, pen...",132050,0.0,NaN,81.0,Sendok Takar,elektronik

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7944 entries, 0 to 7943
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    7944 non-null   int64
 1   product_name  7944 non-null   object
 2   url           7944 non-null   object
 3   description   7736 non-null   object
 4   price         7944 non-null   int64
 5   sold_count    7938 non-null   float64
 6   rating        6760 non-null   float64
 7   total_stock   7938 non-null   float64
 8   category      7944 non-null   object
 9   keyword       7944 non-null   object
dtypes: float64(3), int64(2), object(5)
memory usage: 620.8+ KB

In [16]:
import re
import nltk
from collections import Counter
from nltk.corpus import stopwords

# --- download stopwords bahasa Indonesia (sekali aja perlu jalanin) ---
nltk.download("stopwords")

# --- ambil stopwords Indonesia ---
stopwords_id = set(stopwords.words("indonesian"))

# --- kolom yang akan dianalisis ---
cols_to_check = [
    "product_id", "product_name", "description", 
    "price", "sold_count", "rating", "total_stock", "category"
]

def get_most_common_words(series, n=10):
    text = " ".join(series.dropna().astype(str))
    words = re.findall(r'\w+', text.lower())
    
    filtered = []
    for w in words:
        # skip angka murni
        if w.isdigit():
            continue
        # skip stopwords
        if w in stopwords_id:
            continue
        filtered.append(w)
    
    return Counter(filtered).most_common(n)

# --- loop tiap kolom ---
for col in cols_to_check:
    print(f"\n=== Most Common Words in '{col}' ===")
    common_words = get_most_common_words(df[col], n=10)
    for word, count in common_words:
        print(f"{word}: {count}")

[nltk_data] Downloading package stopwords to /Users/vinn/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

=== Most Common Words in 'product_id' ===

=== Most Common Words in 'product_name' ===
wanita: 1182
pria: 1004
bayi: 876
anak: 798
sekolah: 752
set: 742
tas: 692
paket: 662
celana: 650
alat: 646

=== Most Common Words in 'description' ===
produk: 8982
cm: 8070
bahan: 6006
x: 5820
ukuran: 5110
warna: 3948
kulit: 3928
barang: 3536
cocok: 3470
size: 3318

=== Most Common Words in 'price' ===

=== Most Common Words in 'sold_count' ===

=== Most Common Words in 'rating' ===

=== Most Common Words in 'total_stock' ===

=== Most Common Words in 'category' ===
pria: 860
wanita: 782
android: 524
os: 524
celana: 426
bayi: 370
alat: 352
kaos: 332
tas: 332
ransel: 296

In [17]:
# --- kumpulkan semua kata ---
all_words = []
for col in cols_to_check:
    common_words = get_most_common_words(df[col], n=None)  # ambil semua kata
    all_words.extend(common_words)

# --- gabungkan count dari semua kolom ---
total_counter = Counter()
for word, count in all_words:
    total_counter[word] += count

# --- ambil top 300 ---
top_words = total_counter.most_common(500)

# --- jadikan DataFrame ---
df_top_words1 = pd.DataFrame(top_words, columns=['word', 'count'])
df_top_words1.head

<bound method NDFrame.head of         word  count
0     produk   9036
1         cm   8098
2      bahan   6270
3          x   5898
4     ukuran   5182
..       ...    ...
495    tutup    346
496    beban    346
497    gurih    344
498     area    344
499  memilih    344

[500 rows x 2 columns]>

In [ ]:
## Most Common words dari kedua data

In [18]:
df_top_words_combined = pd.concat([df_top_words1, df_top_words2])
df_top_words_combined = df_top_words_combined.groupby('word', as_index=False)['count'].sum()
df_top_words_combined = df_top_words_combined.sort_values(by='count', ascending=False).reset_index(drop=True)

df_top_words_combined.head(30)

          word  count
0       produk  10047
1           cm   8098
2        bahan   7206
3            x   5898
4       ukuran   5615
5       barang   5329
6        warna   4609
7        kulit   4358
8       sesuai   4339
9        cocok   4220
10  pengiriman   4007
11       paket   3930
12        bayi   3450
13        size   3404
14        anak   3305
15        aman   3184
16      celana   3112
17       bagus   2990
18       mudah   2923
19     lingkar   2870
20         nya   2764
21      wanita   2754
22      nyaman   2748
23     garansi   2668
24        pria   2516
25         tas   2501
26       cepat   2469
27        toko   2362
28        alat   2296
29    membantu   2278

In [ ]:
# Detect Slangs / Bahasa Gaul Indonesia

In [19]:
import re
import pandas as pd

SLANG_SEED = {
    # ketawa / ekspresi
    "wkwk", "wk", "wkwkwk", "hahaha", "hehe", "huhu", "hadeh", "hahaa", "heh", "hihi",
    "huehue", "wkwkw", "hehehe", "hihihi",

    # sapaan / panggilan gaul
    "bro", "brooo", "cuy", "cuyyy", "ciy", "sisss", "gan", "ganzz", "mblooo", "sis", "bosque", "juragan",

    # gaya / slang umum
    "mantul", "mantulll", "mager", "gabut", "alay", "alayyyy", "santuy", "santuyyy", 
    "keren", "kerenz", "cihuy", "cihuyyy", "asyik", "asyikkk", "asik", "yoi", "kuy", 
    "sokap", "parahh", "goks", "mantep", "sip", "ok", "wow", "hah", "yaa", "wkwkw",

    # kata populer sosial media
    "baper", "galau", "nyantai", "kepo", "recehh", "pede", "gas", "gass", "hadehh", "hadehhh"
}

SLANG_RULES = [
    ("repeated_laugh", re.compile(r"^(?:ha|he|hi|hu|wk|wkwk|x){2,}$")),
    ("elongated", re.compile(r"^[a-z]{2,}([a-z])\1{2,}$")),
    ("seeded", re.compile(r"^[a-z]{2,15}$")),  # diperluas jadi 15 huruf
]

def detect_slangs(df_words: pd.DataFrame, min_count: int = 5) -> pd.DataFrame:
    rows = []
    for _, row in df_words.iterrows():
        w = str(row["word"]).lower()
        c = int(row["count"])

        if c < min_count:
            continue
        if not re.fullmatch(r"[a-z0-9]+", w):
            continue

        matched = None
        for name, rx in SLANG_RULES:
            if rx.match(w):
                if name == "seeded" and w not in SLANG_SEED:
                    continue
                matched = name
                break

        if matched:
            rows.append({"word": w, "count": c, "rule": matched})

    return pd.DataFrame(rows).sort_values(["count","word"], ascending=[False, True]).reset_index(drop=True)

# contoh pakai:
df_slangs = detect_slangs(df_top_words_combined, min_count=20)
df_slangs.head(40)

    word  count    rule
0     ok    334  seeded
1  keren    213  seeded

In [20]:
df_slangs['word'].unique()

array(['ok', 'keren'], dtype=object)

In [21]:
slangs_dictionary = {w: "" for w in df_slangs["word"].tolist()}

list(slangs_dictionary.items())[:20]

[('ok', ''), ('keren', '')]

In [22]:
for s in SLANG_SEED:
    if s not in slangs_dictionary:
        slangs_dictionary[s] = ""

list(slangs_dictionary.items())

[('ok', ''),
 ('keren', ''),
 ('kepo', ''),
 ('bosque', ''),
 ('gas', ''),
 ('ciy', ''),
 ('ganzz', ''),
 ('alayyyy', ''),
 ('hihihi', ''),
 ('wkwk', ''),
 ('hah', ''),
 ('sisss', ''),
 ('brooo', ''),
 ('asyik', ''),
 ('asik', ''),
 ('mblooo', ''),
 ('hadehhh', ''),
 ('gabut', ''),
 ('hehehe', ''),
 ('gass', ''),
 ('alay', ''),
 ('mantul', ''),
 ('yoi', ''),
 ('baper', ''),
 ('hadeh', ''),
 ('mantep', ''),
 ('sip', ''),
 ('yaa', ''),
 ('santuyyy', ''),
 ('nyantai', ''),
 ('hahaa', ''),
 ('kerenz', ''),
 ('mager', ''),
 ('galau', ''),
 ('sis', ''),
 ('huhu', ''),
 ('hahaha', ''),
 ('recehh', ''),
 ('mantulll', ''),
 ('sokap', ''),
 ('pede', ''),
 ('hadehh', ''),
 ('hihi', ''),
 ('cuy', ''),
 ('wkwkwk', ''),
 ('cuyyy', ''),
 ('wk', ''),
 ('wkwkw', ''),
 ('cihuy', ''),
 ('goks', ''),
 ('asyikkk', ''),
 ('wow', ''),
 ('cihuyyy', ''),
 ('kuy', ''),
 ('gan', ''),
 ('juragan', ''),
 ('santuy', ''),
 ('hehe', ''),
 ('bro', ''),
 ('parahh', ''),
 ('heh', ''),
 ('huehue', '')]

In [23]:
for k, v in slangs_dictionary.items():
    print(f"{k}: {v}")

ok:
keren:
kepo:
bosque:
gas:
ciy:
ganzz:
alayyyy:
hihihi:
wkwk:
hah:
sisss:
brooo:
asyik:
asik:
mblooo:
hadehhh:
gabut:
hehehe:
gass:
alay:
mantul:
yoi:
baper:
hadeh:
mantep:
sip:
yaa:
santuyyy:
nyantai:
hahaa:
kerenz:
mager:
galau:
sis:
huhu:
hahaha:
recehh:
mantulll:
sokap:
pede:
hadehh:
hihi:
cuy:
wkwkwk:
cuyyy:
wk:
wkwkw:
cihuy:
goks:
asyikkk:
wow:
cihuyyy:
kuy:
gan:
juragan:
santuy:
hehe:
bro:
parahh:
heh:
huehue:

In [24]:
import pandas as pd

all_slangs = list(SLANG_SEED)  

slangs_dictionary = pd.DataFrame({
    "word": all_slangs,
    "rule": ["slang"] * len(all_slangs)
})

slangs_dictionary

      word   rule
0     kepo  slang
1   bosque  slang
2      gas  slang
3      ciy  slang
4    ganzz  slang
..     ...    ...
57      ok  slang
58     bro  slang
59  parahh  slang
60     heh  slang
61  huehue  slang

[62 rows x 2 columns]

In [25]:
import pandas as pd

if 'df_slangs' in globals() and "word" in df_slangs.columns:
    detected_slangs = set(df_slangs["word"].tolist())
else:
    detected_slangs = set()

all_slangs = detected_slangs | set(SLANG_SEED)

df_all_slangs = pd.DataFrame({
    "word": list(all_slangs),
    "rule": ["slang"] * len(all_slangs)
})

df_all_slangs

       word   rule
0   alayyyy  slang
1    hihihi  slang
2      wkwk  slang
3       hah  slang
4     sisss  slang
..      ...    ...
57  cihuyyy  slang
58      gan  slang
59      bro  slang
60      heh  slang
61   huehue  slang

[62 rows x 2 columns]

In [26]:
import re

# ke kata baku terdekat

SLANGS_BAKU = {
    "keren": "bagus",
    "sokap": "tingkah",
    "heh": "haha",
    "galau": "bingung",
    "yaa": "iya",
    "kepo": "penasaran",
    "sip": "oke",
    "parahh": "parah",
    "gas": "lanjut",
    "alayyyy": "norak",
    "kerenz": "bagus",
    "sis": "saudari",
    "mblooo": "jomblo",
    "hadehh": "aduh",
    "hahaa": "haha",
    "brooo": "bro",
    "hihihi": "haha",
    "juragan": "bos",
    "wk": "haha",
    "bro": "bro",
    "kuy": "ayo",
    "bosque": "bos",
    "wow": "wow",
    "cuy": "bro",
    "cihuyyy": "asik",
    "hadeh": "aduh",
    "asik": "menyenangkan",
    "nyantai": "santai",
    "sisss": "saudari",
    "mantulll": "mantap",
    "cuyyy": "bro",
    "gabut": "bosan",
    "hehe": "haha",
    "alay": "norak",
    "santuyyy": "santai",
    "gass": "lanjut",
    "wkwkwk": "haha",
    "santuy": "santai",
    "pede": "percaya diri",
    "wkwk": "haha",
    "huehue": "haha",
    "asyikkk": "menyenangkan",
    "hehehe": "haha",
    "ciy": "bro",
    "cihuy": "asik",
    "goks": "keren",
    "recehh": "sepele",
    "hadehhh": "aduh",
    "mantul": "mantap",
    "mantep": "mantap",
    "hah": "haha",
    "hihi": "haha",
    "asyik": "menyenangkan",
    "wkwkw": "haha",
    "ganzz": "bro",
    "yoi": "iya",
    "baper": "mudah tersinggung",
    "huhu": "sedih",
    "gan": "bro",
    "mager": "malas",
    "hahaha": "haha",
}

In [28]:
list(slangs_dictionary.items())

[('word',
  0       kepo
  1     bosque
  2        gas
  3        ciy
  4      ganzz
         ...
  57        ok
  58       bro
  59    parahh
  60       heh
  61    huehue
  Name: word, Length: 62, dtype: object),
 ('rule',
  0     slang
  1     slang
  2     slang
  3     slang
  4     slang
        ...
  57    slang
  58    slang
  59    slang
  60    slang
  61    slang
  Name: rule, Length: 62, dtype: object)]

In [27]:
import pandas as pd

df_slangs = pd.DataFrame({
    "word": list(SLANGS_BAKU.keys()),
    "rule": ["slang"] * len(SLANGS_BAKU)
})

def build_slang_dict(
    df_slangs: pd.DataFrame,
    keep_unmapped: bool = False
) -> dict[str, str]:
    """
    Membangun dictionary mapping slang dari df_slangs.
    - keep_unmapped=False -> hanya simpan slang yang punya mapping ke kata baku
    - keep_unmapped=True  -> semua slang dimasukkan, tanpa mapping = slang itu sendiri
    """
    mapping = {}
    for _, r in df_slangs[["word", "rule"]].drop_duplicates().iterrows():
        w = str(r["word"]).lower()
        rule = r["rule"] if "rule" in r and pd.notna(r["rule"]) else None

        expanded = SLANGS_BAKU.get(w)

        if expanded:
            mapping[w] = expanded
        else:
            if keep_unmapped:
                mapping[w] = w 

    return mapping

slang_dict = build_slang_dict(df_slangs, keep_unmapped=True)

print({k: slang_dict[k] for k in list(slang_dict)[:20]})

import json
with open("slangs_mapping.json", "w", encoding="utf-8") as f:
    json.dump(slang_dict, f, indent=2, ensure_ascii=False)

print("Slangs dictionary siap digunakan")

{'keren': 'bagus', 'sokap': 'tingkah', 'heh': 'haha', 'galau': 'bingung', 'yaa': 'iya', 'kepo': 'penasaran', 'sip': 'oke', 'parahh': 'parah', 'gas': 'lanjut', 'alayyyy': 'norak', 'kerenz': 'bagus', 'sis': 'saudari', 'mblooo': 'jomblo', 'hadehh': 'aduh', 'hahaa': 'haha', 'brooo': 'bro', 'hihihi': 'haha', 'juragan': 'bos', 'wk': 'haha', 'bro': 'bro'}
Slangs dictionary siap digunakan

In [ ]:
# Detect contractions

In [29]:
import pandas as pd

INDO_CONTRACTIONS = {
    "gk": "tidak",
    "gak": "tidak",
    "nggak": "tidak",
    "ga": "tidak",
    "yg": "yang",
    "dgn": "dengan",
    "dr": "dari",
    "sdh": "sudah",
    "blm": "belum",
    "sbg": "sebagai",
    "tp": "tapi",
    "klo": "kalau",
    "klu": "kalau",
    "krn": "karena",
    "dll": "dan lain-lain",
    "dst": "dan seterusnya"
}

def detect_indo_contractions_count(df_words: pd.DataFrame) -> pd.DataFrame:
    """
    Mendeteksi contractions Bahasa Indonesia dari df_words,
    menghitung jumlah kemunculannya.
    df_words: DataFrame dengan kolom 'word' (token)
    """
    counter = {}
    for w in df_words["word"]:
        token = str(w).lower()
        if token in INDO_CONTRACTIONS:
            counter[token] = counter.get(token, 0) + 1
    
    rows = [{"word": k, "count": v, "rule": "indo_contraction"} for k, v in counter.items()]
    return pd.DataFrame(rows).sort_values(["count", "word"], ascending=[False, True]).reset_index(drop=True)

df_indo_contractions = detect_indo_contractions_count(df_top_words_combined)
df_indo_contractions.head(40)

  word  count              rule
0  dgn      1  indo_contraction
1  dll      1  indo_contraction
2   ga      1  indo_contraction
3  gak      1  indo_contraction
4   gk      1  indo_contraction
5  sdh      1  indo_contraction
6   tp      1  indo_contraction
7   yg      1  indo_contraction

In [30]:
df_indo_contractions['word'].unique()

array(['dgn', 'dll', 'ga', 'gak', 'gk', 'sdh', 'tp', 'yg'], dtype=object)

In [31]:
contractions_dictionary = {w: "" for w in df_indo_contractions["word"].tolist()}

list(contractions_dictionary.items())[:20]

[('dgn', ''),
 ('dll', ''),
 ('ga', ''),
 ('gak', ''),
 ('gk', ''),
 ('sdh', ''),
 ('tp', ''),
 ('yg', '')]

In [32]:
for i in INDO_CONTRACTIONS:
    if i not in contractions_dictionary:
        contractions_dictionary[i] = ""

list(contractions_dictionary.items())

[('dgn', ''),
 ('dll', ''),
 ('ga', ''),
 ('gak', ''),
 ('gk', ''),
 ('sdh', ''),
 ('tp', ''),
 ('yg', ''),
 ('nggak', ''),
 ('dr', ''),
 ('blm', ''),
 ('sbg', ''),
 ('klo', ''),
 ('klu', ''),
 ('krn', ''),
 ('dst', '')]

In [33]:
for k, v in contractions_dictionary.items():
    print(f"{k}: {v}")

dgn:
dll:
ga:
gak:
gk:
sdh:
tp:
yg:
nggak:
dr:
blm:
sbg:
klo:
klu:
krn:
dst:

In [34]:
import pandas as pd

all_contractions = list(INDO_CONTRACTIONS)  

contractions_dictionary = pd.DataFrame({
    "word": all_contractions,
    "rule": ["contractions"] * len(all_contractions)
})

contractions_dictionary

     word          rule
0      gk  contractions
1     gak  contractions
2   nggak  contractions
3      ga  contractions
4      yg  contractions
5     dgn  contractions
6      dr  contractions
7     sdh  contractions
8     blm  contractions
9     sbg  contractions
10     tp  contractions
11    klo  contractions
12    klu  contractions
13    krn  contractions
14    dll  contractions
15    dst  contractions

In [35]:
import pandas as pd

if 'df_indo_contractions' in globals() and "word" in df_indo_contractions.columns:
    detected_contract = set(df_indo_contractions["word"].tolist())
else:
    detected_contract = set()

all_contractions = detected_contract | set(INDO_CONTRACTIONS)

df_all_contractions = pd.DataFrame({
    "word": list(all_contractions),
    "rule": ["contractions"] * len(all_contractions)
})

df_all_contractions

     word          rule
0     sbg  contractions
1     gak  contractions
2     dst  contractions
3      tp  contractions
4     klu  contractions
5      gk  contractions
6     sdh  contractions
7     dll  contractions
8     blm  contractions
9   nggak  contractions
10     yg  contractions
11    krn  contractions
12     ga  contractions
13    klo  contractions
14    dgn  contractions
15     dr  contractions

In [36]:
import re

CONTRACTIONS_BAKU = {
    "gk": "tidak",
    "gak": "tidak",
    "nggak": "tidak",
    "ga": "tidak",
    "yg": "yang",
    "dgn": "dengan",
    "dr": "dari",
    "sdh": "sudah",
    "blm": "belum",
    "sbg": "sebagai",
    "tp": "tapi",
    "klo": "kalau",
    "klu": "kalau",
    "krn": "karena",
    "dll": "dan lain-lain",
    "dst": "dan seterusnya"
}

In [37]:
list(contractions_dictionary.items())

[('word',
  0        gk
  1       gak
  2     nggak
  3        ga
  4        yg
  5       dgn
  6        dr
  7       sdh
  8       blm
  9       sbg
  10       tp
  11      klo
  12      klu
  13      krn
  14      dll
  15      dst
  Name: word, dtype: object),
 ('rule',
  0     contractions
  1     contractions
  2     contractions
  3     contractions
  4     contractions
  5     contractions
  6     contractions
  7     contractions
  8     contractions
  9     contractions
  10    contractions
  11    contractions
  12    contractions
  13    contractions
  14    contractions
  15    contractions
  Name: rule, dtype: object)]

In [38]:
import pandas as pd

df_indo_contractions = pd.DataFrame({
    "word": list(INDO_CONTRACTIONS.keys()),
    "rule": ["contractions"] * len(INDO_CONTRACTIONS)
})

def build_contractions_dict(
    df_indo_contractions: pd.DataFrame,
    keep_unmapped: bool = False
) -> dict[str, str]:
    """
    Membangun dictionary mapping contractions dari df_indo_contractions.
    - keep_unmapped=False -> hanya simpan contractions yang punya mapping ke kata baku
    - keep_unmapped=True  -> semua contractions dimasukkan, tanpa mapping = contractions itu sendiri
    """
    mapping = {}
    for _, r in df_indo_contractions[["word", "rule"]].drop_duplicates().iterrows():
        w = str(r["word"]).lower()
        rule = r["rule"] if "rule" in r and pd.notna(r["rule"]) else None

        expanded = CONTRACTIONS_BAKU.get(w)

        if expanded:
            mapping[w] = expanded
        else:
            if keep_unmapped:
                mapping[w] = w 

    return mapping

contractions_dictionary = build_contractions_dict(df_indo_contractions, keep_unmapped=True)

print({k: contractions_dictionary[k] for k in list(contractions_dictionary)[:20]})

import json
with open("contractions_mapping.json", "w", encoding="utf-8") as f:
    json.dump(contractions_dictionary, f, indent=2, ensure_ascii=False)

print("Contractions dictionary siap digunakan")

{'gk': 'tidak', 'gak': 'tidak', 'nggak': 'tidak', 'ga': 'tidak', 'yg': 'yang', 'dgn': 'dengan', 'dr': 'dari', 'sdh': 'sudah', 'blm': 'belum', 'sbg': 'sebagai', 'tp': 'tapi', 'klo': 'kalau', 'klu': 'kalau', 'krn': 'karena', 'dll': 'dan lain-lain', 'dst': 'dan seterusnya'}
Contractions dictionary siap digunakan

Detect Emoji

In [39]:
import pandas as pd
import re
import json

# === Regex Emoji ===
EMOJI_RE = re.compile(
    "[\U0001F600-\U0001F64F"  # emotikon
    "\U0001F300-\U0001F5FF"   # simbol & pictographs
    "\U0001F680-\U0001F6FF"   # transport
    "\U0001F700-\U0001F77F"   # alchemical
    "\U0001F780-\U0001F7FF"   # geometric shapes
    "\U0001F800-\U0001F8FF"   # arrows
    "\U0001F900-\U0001F9FF"   # tambahan emotikon
    "\U0001FA70-\U0001FAFF"   # simbol tambahan
    "\u2600-\u26FF"           # simbol misc (☀, ☂, dll)
    "\u2700-\u27BF"           # dingbats (✂, ✔, dll)
    "]+", flags=re.UNICODE
)

def extract_emojis(text: str) -> list[str]:
    if not isinstance(text, str):
        return []
    return EMOJI_RE.findall(text)

def detect_top_emojis(df: pd.DataFrame, top_n: int = 50) -> pd.DataFrame:
    """Ambil top-N emoji paling sering dari kolom teks (auto deteksi)."""
    emoji_counts = {}

    text_col = max(df.select_dtypes(include="object").columns,
                   key=lambda c: df[c].astype(str).str.len().mean())

    for txt in df[text_col].dropna():
        for emo in extract_emojis(txt):
            for ch in emo:
                emoji_counts[ch] = emoji_counts.get(ch, 0) + 1

    df_emoji = (
        pd.DataFrame(list(emoji_counts.items()), columns=["emoji", "count"])
        .sort_values("count", ascending=False)
        .reset_index(drop=True)
    )
    return df_emoji.head(top_n)

df_reviews = pd.read_json("datas/reviews_combined.json")
df_top_emoji = detect_top_emojis(df_reviews, top_n=50)

print(df_top_emoji)

emoji_dict = {row["emoji"]: "" for _, row in df_top_emoji.iterrows()}
with open("datas/emoji_dict.json", "w", encoding="utf-8") as f:
    json.dump(emoji_dict, f, ensure_ascii=False, indent=2)

   emoji  count
0      👍   1063
1      🙏    414
2      🥰    372
3      🏻    366
4      😍    202
5      😁    103
6      🫶     86
7      😭     85
8      ❤     72
9      😊     67
10     🌟     55
11     👌     50
12     🤗     49
13     🤲     49
14     🫰     45
15     🏼     43
16     🤩     42
17     ✅     40
18     🤭     35
19     🔥     35
20     🤣     34
21     😘     33
22     😄     32
23     ✨     31
24     😅     29
25     ☺     28
26     🔯     23
27     😂     22
28     🤍     22
29     😇     21
30     🥲     19
31     💯     18
32     🤔     17
33     💗     14
34     🙂     13
35     💕     12
36     🥹     12
37     😻     12
38     🥵     11
39     🏾     11
40     🤤     11
41     👏     11
42     😀     10
43     😔      9
44     🙌      9
45     😚      9
46     🥺      9
47     ♡      9
48     🙈      8
49     🤦      8

In [40]:
emoji_mapping = {
  "👍": "bagus",
  "🙏": "terima kasih",
  "🥰": "suka banget",
  "🏻": "kulit terang",
  "😍": "sangat suka",
  "😁": "senang",
  "🫶": "support",
  "😭": "terharu",
  "❤": "cinta",
  "😊": "senang",
  "🌟": "kualitas bagus",
  "👌": "oke",
  "🤗": "nyaman",
  "🤲": "berharap produk bermanfaat",
  "🫰": "sangat suka",
  "🏼": "kulit sedang",
  "🤩": "terpesona dengan produk",
  "✅": "produk sesuai deskripsi",
  "🤭": "malu-malu tapi senang",
  "🔥": "produk keren",
  "🤣": "ngakak",
  "😘": "suka banget produknya",
  "😄": "senang",
  "✨": "produk istimewa",
  "😅": "ketawa canggung",
  "☺": "bahagia",
  "🔯": "simbol bintang",
  "😂": "lucu",
  "🤍": "cinta produk",
  "😇": "puas",
  "🥲": "terharu",
  "💯": "mantap banget",
  "🤔": "ragu-ragu",
  "💗": "cinta produk",
  "🙂": "senyum",
  "💕": "suka banget",
  "🥹": "terharu senang",
  "😻": "suka banget",
  "🥵": "excited dengan produk",
  "🏾": "kulit gelap",
  "🤤": "produk menarik banget",
  "👏": "apresiasi ke penjual",
  "😀": "senyum puas",
  "😔": "sedikit kecewa",
  "🙌": "senang banget",
  "😚": "senang",
  "🥺": "terharu",
  "♡": "cinta produk",
  "🙈": "malu-malu",
  "🤦": "kecewa"
}

In [41]:
with open("emoji_dictionary.json", "w", encoding="utf-8") as f:
    json.dump(emoji_mapping, f, ensure_ascii=False, indent=4)

In [43]:
import json

with open("datas/reviews_combined.json", "r", encoding="utf-8") as f:
    reviews = json.load(f)   # <-- list of string

with open("dictionary/emoji_dictionary.json", "r", encoding="utf-8") as f:
    emoji_mapping = json.load(f)

def map_emojis(text, mapping):
    if not isinstance(text, str):
        return text
    for emo, arti in mapping.items():
        text = text.replace(emo, arti)  # ⬅️ langsung replace
    return text

reviews_mapped = [map_emojis(r, emoji_mapping) for r in reviews]

with open("datas/reviews_mapped.json", "w", encoding="utf-8") as f:
    json.dump(reviews_mapped, f, ensure_ascii=False, indent=2)

print("reviews_mapped.json berhasil dibuat (emoji sudah diganti arti bahasa Indonesia)")

reviews_mapped.json berhasil dibuat (emoji sudah diganti arti bahasa Indonesia)